name: Run JUnit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Check out code
      uses: actions/checkout@v4

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Run tests
      run: ./gradlew test

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: build/test-results/test

    - name: Upload Test Reports
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: build/reports/tests/test
